import type { MetadataRoute } from "next";

import { siteMeta } from "@/app/data";

/**
 * `/robots.txt` — generated by Next.js 16 file-based metadata route.
 *
 * Allows all crawlers on everything except `/api/*` (server-only stubs
 * for contact + newsletter forms, not meant to be indexed).
 *
 * Sitemap is referenced as an absolute URL so crawlers can find it
 * regardless of which host/CDN edge serves `robots.txt`.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: "/api/",
      },
    ],
    sitemap: `${siteMeta.url}/sitemap.xml`,
    host: siteMeta.url,
  };
}
